package in.ac.iitb.XMLAnnotator;
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 10:21:39 PM BRT 
//




import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="iitb.QuantitySearch.Query" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="queryID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="numericID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="queryString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="descriptionString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="standardUnitName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="answerSet">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "iitbQuantitySearchQuery"
})
@XmlRootElement(name = "temporalQueries")
public class TemporalQueries {

    @XmlElement(name = "iitb.QuantitySearch.Query", required = true)
    protected List<TemporalQueries.IitbQuantitySearchQuery> iitbQuantitySearchQuery;

    /**
     * Gets the value of the iitbQuantitySearchQuery property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iitbQuantitySearchQuery property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIitbQuantitySearchQuery().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TemporalQueries.IitbQuantitySearchQuery }
     * 
     * 
     */
    public List<TemporalQueries.IitbQuantitySearchQuery> getIitbQuantitySearchQuery() {
        if (iitbQuantitySearchQuery == null) {
            iitbQuantitySearchQuery = new ArrayList<TemporalQueries.IitbQuantitySearchQuery>();
        }
        return this.iitbQuantitySearchQuery;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="queryID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="numericID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="queryString" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="descriptionString" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="standardUnitName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="answerSet">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "queryID",
        "numericID",
        "queryString",
        "descriptionString",
        "standardUnitName",
        "answerSet"
    })
    public static class IitbQuantitySearchQuery {

        @XmlElement(required = true)
        protected String queryID;
        protected int numericID;
        @XmlElement(required = true)
        protected String queryString;
        @XmlElement(required = true)
        protected String descriptionString;
        @XmlElement(required = true)
        protected String standardUnitName;
        @XmlElement(required = true)
        protected TemporalQueries.IitbQuantitySearchQuery.AnswerSet answerSet;

        /**
         * Gets the value of the queryID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQueryID() {
            return queryID;
        }

        /**
         * Sets the value of the queryID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQueryID(String value) {
            this.queryID = value;
        }

        /**
         * Gets the value of the numericID property.
         * 
         */
        public int getNumericID() {
            return numericID;
        }

        /**
         * Sets the value of the numericID property.
         * 
         */
        public void setNumericID(int value) {
            this.numericID = value;
        }

        /**
         * Gets the value of the queryString property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQueryString() {
            return queryString;
        }

        /**
         * Sets the value of the queryString property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQueryString(String value) {
            this.queryString = value;
        }

        /**
         * Gets the value of the descriptionString property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescriptionString() {
            return descriptionString;
        }

        /**
         * Sets the value of the descriptionString property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescriptionString(String value) {
            this.descriptionString = value;
        }

        /**
         * Gets the value of the standardUnitName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStandardUnitName() {
            return standardUnitName;
        }

        /**
         * Sets the value of the standardUnitName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStandardUnitName(String value) {
            this.standardUnitName = value;
        }

        /**
         * Gets the value of the answerSet property.
         * 
         * @return
         *     possible object is
         *     {@link TemporalQueries.IitbQuantitySearchQuery.AnswerSet }
         *     
         */
        public TemporalQueries.IitbQuantitySearchQuery.AnswerSet getAnswerSet() {
            return answerSet;
        }

        /**
         * Sets the value of the answerSet property.
         * 
         * @param value
         *     allowed object is
         *     {@link TemporalQueries.IitbQuantitySearchQuery.AnswerSet }
         *     
         */
        public void setAnswerSet(TemporalQueries.IitbQuantitySearchQuery.AnswerSet value) {
            this.answerSet = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="string" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "string"
        })
        public static class AnswerSet {

            @XmlElement(required = true)
            protected String string;

            /**
             * Gets the value of the string property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getString() {
                return string;
            }

            /**
             * Sets the value of the string property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setString(String value) {
                this.string = value;
            }

        }

    }

}
